name: On Main Push

on:
    push:
        branches:
            - "main"

jobs:
    main:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Get Package Version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@main

            - name: Use Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
            - run: |
                  npm ci
                  npm run build
                  npm pack

            - name: Upload Release Assets
              run: gh release create v${{ steps.package-version.outputs.current-version }} -t v${{ steps.package-version.outputs.current-version }} --target main -F ./*.tgz
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
